# Site settings
title: ProgSoc
email: contactus@progsoc.co.uk
description: > # this means to ignore newlines until "baseurl:"
    We are the University of Sussex Programming Society
baseurl: "/other-website" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
facebook_page: facebook.com/ProgSocSussex
twitter_username: ProgSocSussex
github_username:  sussex-progsoc

# Build settings
markdown: kramdown

# Syntax highlighting
highlighter: pygments

# Collections. Unstable.
collections:
    problems:
        output: true
        
excerpt_separator: ""